name: Test
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.0

      - name: Install Go
        uses: actions/setup-go@v7.0.0
        with:
          go-version: "1.25"
          # setup-go provides module/build caching out of the box.

      - name: Test
        run: go test -race ./...
